[package]
name = "woodo"
description = "It's a weird tree."
repository = "https://github.com/knpwrs/woodo"
license = "MIT"
version = "1.0.1"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
nix = "0.23.1"
